apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: orderapp
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-base64-encoded"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: orderapp
type: Opaque
stringData:
  MONGODB_URI: "mongodb://user_admin:user_pass@mongodb-user:27017/user_db?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
  namespace: orderapp
type: Opaque
stringData:
  DB_USER: "product_user"
  DB_PASSWORD: "product_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: orderapp
type: Opaque
stringData:
  DB_USER: "order_user"
  DB_PASSWORD: "order_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: orderapp
type: Opaque
stringData:
  MONGODB_URI: "mongodb://payment_admin:payment_pass@mongodb-payment:27017/payment_db?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-providers-secret
  namespace: orderapp
type: Opaque
stringData:
  STRIPE_SECRET_KEY: "sk_live_your_stripe_secret_key"
  PAYPAL_CLIENT_ID: "your_paypal_client_id"
  PAYPAL_CLIENT_SECRET: "your_paypal_client_secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-redis-secret
  namespace: orderapp
type: Opaque
stringData:
  REDIS_PASSWORD: "notification_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: orderapp
type: Opaque
stringData:
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
